name: pharmy_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Http
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.0


  #State management
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3

  #Ui
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.7

  extended_image: ^8.1.1
  flutter_spinkit: ^5.2.0
  lottie: ^2.4.0
  shimmer: ^3.0.0
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
 # connectivity_plus: ^4.0.2
  flutter_localizations:
    sdk: flutter
 # firebase_messaging: ^14.7.10
  intl: any
  flutter_local_notifications: ^16.3.0
  url_launcher: ^6.2.1
  flutter_switch: ^0.3.2
  sms_autofill: ^2.3.0
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  flutter_swipe_button: ^2.1.1+1
#  lite_rolling_switch: ^1.0.1
  slide_action: ^0.0.2
  d_chart: ^2.6.7
  slide_to_act: ^2.0.2
  package_info_plus:
  flutter_widget_from_html:
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/menu.png"




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/lotties/
    - assets/images/
  fonts:
    - family: FrutigerLTArabic
      fonts:
        - asset: fonts/FrutigerLTArabic45Light.ttf
          weight: 300
        - asset: fonts/FrutigerLTArabic55Roman.ttf
          weight: 600
        - asset: fonts/FrutigerLTArabic65Bold.ttf
          weight: 900
